
export const ADMIN_DB = [
    {
        id: 1,
        email: 'asd123@gmail.com',
        firstName: 'Umesh',
        lastName: 'Mandal',
        password: 'aaaaaa',
        role: 'admin',
        color: ['Green'],
        status: 1,
        country: 'Nepal',
    },
    {
        id: 2,
        email: 'asd123@gmail.com',
        firstName: 'Ganesh',
        lastName: 'adhikari',
        password: 'ganuaa',
        role: 'admin',
        color: ['Pink'],
        status: 2,
        country: 'Bangladesh',
    },

    {
        id: 3,
        email: 'asd123@gmail.com',
        firstName: 'Jaydeep',
        lastName: 'sah',
        password: 'japuaa',
        role: 'admin',
        color: ['White'],
        status: 3,
        country: 'USA',
    },
    {
        id: 4,
        email: 'asd123@gmail.com',
        firstName: 'Binod',
        lastName: 'Shrestha',
        password: 'baaaaa',
        role: 'manager',
        color: ['Green', 'White'],
        status: 4,
        country: 'Germany',
    },
    {
        id: 5,
        email: 'manager@gmail.com',
        firstName: 'Hari',
        lastName: 'Suwal',
        password: 'manager',
        role: 'manager',
        color: ['Green', 'Purple'],
        status: 4,
        country: 'Bhutan',
    },
    {
        id: 6,
        email: 'rambo@gmail.com',
        firstName: 'Ram',
        lastName: 'Mandal',
        password: 'ramboo',
        role: 'manager',
        color: ['Black', 'red'],
        status: 1,
        country: 'Afghanistan',
    },
    {
        id: 7,
        email: 'hamro@gmail.com',
        firstName: 'Umesh',
        lastName: 'Mandal',
        password: '9843223667',
        role: 'user',
        color: ['red', 'Blue'],
        status: 2,
        country: 'Maldives',
    },
    {
        id: 8,
        email: 'ccc@gmail.com',
        firstName: 'Umesh',
        lastName: 'Mandal',
        password: 'caaaaa',
        role: 'user',
        color: ['White', 'Pink'],
        status: 4,
        country: 'China',
    },
    {
        id: 9,
        email: 'we@gmail.com',
        firstName: 'Umesh',
        lastName: 'Mandal',
        password: 'wewewe',
        role: 'user',
        color: ['Yellow', 'Purple'],
        status: 3,
        country: 'Japan',
    },
    {
        id: 10,
        email: 'user@gmail.com',
        firstName: 'Umedsh',
        lastName: 'Mandadl',
        password: 'userer',
        role: 'user',
        color: ['Black', 'White'],
        status: 1,
        country: 'North Korea',
    }
];